### ISSUE TITLE
About the bottom menu

### ISSUE THREAD

**Issue by GBergue** [mysterious588/Life-Assistant#2]
When you don't have tasks incompleted or completed, the app should show blank the tasks RecyclerView and some text like "No tasks to show" in my opinion

![WhatsApp Image 2020-09-17 at 16 28 35 (2)](https://user-images.githubusercontent.com/71409251/93518263-f68e6780-f902-11ea-94b6-6d9a6fc34dad.jpeg)
![WhatsApp Image 2020-09-17 at 16 28 35 (1)](https://user-images.githubusercontent.com/71409251/93518265-f726fe00-f902-11ea-868a-1e81b4ccb2d6.jpeg)
![WhatsApp Image 2020-09-17 at 16 28 35](https://user-images.githubusercontent.com/71409251/93518266-f726fe00-f902-11ea-94e9-856e99332270.jpeg)

**Comment by mysterious588** [comment]
Yeah, will add a text view showing that no tasks are available.

However, there is an issue when you display the content of an empty recycler view here:

For example, there are no completed tasks now, so it should show an empty recycler view:
- sometimes it shows nothing as expected
![Expected image](https://user-images.githubusercontent.com/43171921/93530814-7e459780-f93e-11ea-9ceb-e60448fbe1db.jpg)

- sometimes it shows the items of the previous menu
![bugged image](https://user-images.githubusercontent.com/43171921/93530830-84d40f00-f93e-11ea-94af-9eadbaf19ebd.jpg)

Been trying to fix this for eternity but still no clue

**Comment by GBergue** [comment]
Yeah I found that problem too, i'm trying to understand better the code, because i'm starting in android development, We will find a solution

**Comment by GBergue** [comment]
I have an idea, i tried, but i didn't know how to continue, see my code https://github.com/GBergue/Test
My idea is to create 3 fragments 1 for each option in menu

**Comment by mysterious588** [comment]
Unfortunately, it still won't work, let's say that the recycler view has one item now, and then you decided to delete that item, the bug would still be present and when you delete the item it would still be shown in the recycler view

**Comment by mysterious588** [comment]
Finally, fixed by adding null entries to the database in the "onCreate"
